[project]
name = "fess38.common.lib_requirements"
version = "2023.10.14"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
