[project]
name = "fess38.util"
version = "2023.11.05"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools]
packages = ["fess38.util"]
package-dir = { "fess38.util" = "src" }

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
