[project]
name = "fess38.training"
version = "2023.11.19"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools.package-dir]
"fess38.training" = "src"
"fess38.training.linear" = "src/linear"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
