project_dir: ???
config_path: configs/config.yaml
operation_runner_path: tools/operation_runner/__main__.py

hydra:
  job:
    chdir: true
    env_set:
      DVC_NO_ANALYTICS: "1"
  run:
    dir: ${project_dir}/outputs
