[project]
name = "fess38.data_processing"
version = "2023.10.22"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools]
packages = [
    "fess38.data_processing.backend",
    "fess38.data_processing.io",
    "fess38.data_processing.operations",
    "fess38.data_processing.operations.filters",
]
package-dir = { "fess38.data_processing.backend" = "src/backend", "fess38.data_processing.io" = "src/io", "fess38.data_processing.operations" = "src/operations", "fess38.data_processing.operations.filters" = "src/operations/filters" }

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
