name: Check package on push
on: [push]
permissions:
  actions: write
  contents: read
jobs:
  pre_job:
    name: Check if previous jobs should be cancelled or skip current job
    continue-on-error: true
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
          cancel_others: 'true'
  build:
    name: Run linters and tests
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Free disk space
        # Free github action workers guarantee only 14GB of disk space.
        # To make more room for the build, we remove some of the tools we don't need.
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html
          pip install --no-cache-dir ytsaurus-yson==0.4.3 'evals @ git+https://github.com/openai/evals.git@bd3b4d0afa7785f0374c46c32a32dd4c55105c28'
          pip install --no-cache-dir trafilatura==1.6.2
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
      - name: Run pytest
        run: |
          pytest tests
      - name: Run isort
        run: |
          isort --check-only --diff --profile black .
      - name: Run black
        run: |
          black --check --diff .
      - name: Run flake8
        run: |
          flake8 .
  check:
    name: Check if all jobs succeeded
    if: always()
    needs:
    - pre_job
    - build
    runs-on: Ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        allowed-skips: build
        jobs: ${{ toJSON(needs) }}
